[2023-05-26 12:49:38,022] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-04-02T06:00:00+00:00 [queued]>
[2023-05-26 12:49:38,037] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-04-02T06:00:00+00:00 [queued]>
[2023-05-26 12:49:38,039] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-26 12:49:38,041] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-05-26 12:49:38,042] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-26 12:49:38,064] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-04-02 06:00:00+00:00
[2023-05-26 12:49:38,073] {standard_task_runner.py:52} INFO - Started process 872 to run task
[2023-05-26 12:49:38,079] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2023-04-02T06:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpdkzwwvdh', '--error-file', '/tmp/tmpd073o8j8']
[2023-05-26 12:49:38,081] {standard_task_runner.py:80} INFO - Job 62: Subtask local_to_gcs_task
[2023-05-26 12:49:38,164] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-04-02T06:00:00+00:00 [running]> on host ca6ba07bb7b3
[2023-05-26 12:49:38,230] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-05-26 12:49:38,289] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-02T06:00:00+00:00
[2023-05-26 12:49:38,542] {python.py:173} INFO - Done. Returned value was: None
[2023-05-26 12:49:38,563] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230402T060000, start_date=20230526T124938, end_date=20230526T124938
[2023-05-26 12:49:38,615] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-26 12:49:38,670] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-26 13:30:26,008] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-04-02T06:00:00+00:00 [queued]>
[2023-05-26 13:30:26,025] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-04-02T06:00:00+00:00 [queued]>
[2023-05-26 13:30:26,026] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-26 13:30:26,028] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-05-26 13:30:26,029] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-26 13:30:26,052] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-04-02 06:00:00+00:00
[2023-05-26 13:30:26,060] {standard_task_runner.py:52} INFO - Started process 2113 to run task
[2023-05-26 13:30:26,065] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2023-04-02T06:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmplugvoo3s', '--error-file', '/tmp/tmpjh19e_yv']
[2023-05-26 13:30:26,067] {standard_task_runner.py:80} INFO - Job 74: Subtask local_to_gcs_task
[2023-05-26 13:30:26,149] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-04-02T06:00:00+00:00 [running]> on host ca6ba07bb7b3
[2023-05-26 13:30:26,215] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-05-26 13:30:26,266] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-02T06:00:00+00:00
[2023-05-26 13:30:26,287] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/eugene/Personal_Projects/Data_Project/app/airflow/dags/data_ingestion_gcs.py", line 51, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eugene/Personal_Projects/Data_Project/app/airflow/output_2023-04.parquet'
[2023-05-26 13:30:26,319] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230402T060000, start_date=20230526T133026, end_date=20230526T133026
[2023-05-26 13:30:26,335] {standard_task_runner.py:97} ERROR - Failed to execute job 74 for task local_to_gcs_task ([Errno 2] No such file or directory: '/Users/eugene/Personal_Projects/Data_Project/app/airflow/output_2023-04.parquet'; 2113)
[2023-05-26 13:30:26,360] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-26 13:30:26,418] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
