[2023-05-26 12:24:44,323] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-05-24T00:00:00+00:00 [queued]>
[2023-05-26 12:24:44,359] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-05-24T00:00:00+00:00 [queued]>
[2023-05-26 12:24:44,368] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-26 12:24:44,376] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-05-26 12:24:44,395] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-26 12:24:44,460] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-05-24 00:00:00+00:00
[2023-05-26 12:24:44,481] {standard_task_runner.py:52} INFO - Started process 180 to run task
[2023-05-26 12:24:44,489] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2023-05-24T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmp2e2a1o2o', '--error-file', '/tmp/tmp1mk05b2b']
[2023-05-26 12:24:44,495] {standard_task_runner.py:80} INFO - Job 52: Subtask download_dataset_task
[2023-05-26 12:24:44,677] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-05-24T00:00:00+00:00 [running]> on host ca6ba07bb7b3
[2023-05-26 12:24:44,808] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-24T00:00:00+00:00
[2023-05-26 12:24:44,813] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-26 12:24:44,815] {subprocess.py:74} INFO - Running command: ['bash', '-c', "curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{execution_date.strftime('%Y-%m')}.parquet > /Users/eugene/Personal_Projects/Data_Project/app/***/yellow_tripdata_{execution_date.strftime('%Y-%m')}.parquet"]
[2023-05-26 12:24:44,838] {subprocess.py:85} INFO - Output:
[2023-05-26 12:24:44,841] {subprocess.py:92} INFO - bash: -c: line 1: syntax error near unexpected token `('
[2023-05-26 12:24:44,842] {subprocess.py:92} INFO - bash: -c: line 1: `curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{execution_date.strftime('%Y-%m')}.parquet > /Users/eugene/Personal_Projects/Data_Project/app/***/yellow_tripdata_{execution_date.strftime('%Y-%m')}.parquet'
[2023-05-26 12:24:44,844] {subprocess.py:96} INFO - Command exited with return code 2
[2023-05-26 12:24:44,862] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-05-26 12:24:44,870] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230524T000000, start_date=20230526T122444, end_date=20230526T122444
[2023-05-26 12:24:44,892] {standard_task_runner.py:97} ERROR - Failed to execute job 52 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 2.; 180)
[2023-05-26 12:24:44,914] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-26 12:24:44,978] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
